env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "P+0QBd9YJZC/JrWheHWBDr7DQKFZ8ZhTO6X2ix17r7kCmOfRO6s4OnfSzU0/wzpK61ri+sh6UD/QKZIG+z+G0z0UPz1DvbeyOFNIjIOpSL0FUwRJMtZR3oGAv1UiuLJ6LEbLcahF2MPEX5EEF3WVdwyEuc/6adCvrZTDN22BDPw="

addons:
  coverity_scan:
    project:
      name: "ElfoLiNk/ProgettoPiattaformeSW"
      description: "Build submitted via Travis CI"
    notification_email: matteo_gazzetta@hotmail.it
    build_command_prepend: "qmake"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
 
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt54-trusty
    - sudo apt-get update
    - sudo apt-get install -y qt54base qt54declarative qt54webengine qt54multimedia qt54imageformats qt54-meta
    - sudo source /opt/qt54/bin/qt54-env.sh
script:
    - qmake -v
    - qmake
    - make