sudo: required
dist: trusty
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt57base qt57declarative qt57webengine qt57multimedia qt57imageformats

script:
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake
  - make


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "P+0QBd9YJZC/JrWheHWBDr7DQKFZ8ZhTO6X2ix17r7kCmOfRO6s4OnfSzU0/wzpK61ri+sh6UD/QKZIG+z+G0z0UPz1DvbeyOFNIjIOpSL0FUwRJMtZR3oGAv1UiuLJ6LEbLcahF2MPEX5EEF3WVdwyEuc/6adCvrZTDN22BDPw="

addons:
  coverity_scan:
    project:
      name: "ElfoLiNk/ImageStenography"
      description: "Build submitted via Travis CI"
    notification_email: matteo_gazzetta@hotmail.it
    build_command_prepend: "qmake"
    build_command:   "make -j4"
    branch_pattern: master